### ISSUE TITLE
Question about style of coding

### ISSUE THREAD

**Issue by Mustwey** [Exunys/Roblox-Functions-Library#1]
have you ever considered using a more complex workflow, for the longest time, i have been using your repos to learn how to make scripts, but now that I'm older, I would like to challenge myself with more well-written projects like orca[https://github.com/richie0866/orca]
do you have any plans on continuing such projects and if so are you willing to design it better? I would love to learn how you would go about it

**Comment by Exunys** [comment]
My workstyle or to say, signature handwriting, is a mix between vanilla Lua and Luau (I just don't utilize their fancy type checking and generics). These sort of repositories are kind of modern because they use optimization techniques that is only on Luau. I can reference as an example JavaScript and TypeScript, I can sort of imagine my code being written in a JavaScript style and theirs in a TypeScript one. Here's an example of what I am trying to say:

Luau
```lua
local stringOrNumber: string | number = "foo" -- This variable can ONLY be a string or an integer

if type(stringOrNumber) == "string" then
    local onlyString: string = stringOrNumber -- ok
    local onlyNumber: number = stringOrNumber -- not ok
end

if type(stringOrNumber) ~= "string" then
    local onlyString: string = stringOrNumber -- not ok
    local onlyNumber: number = stringOrNumber -- ok
end
```

Lua
```lua
local stringOrNumber = "foo" -- Lua automatically assigns the type

assert(type(stringOrNumber) == "string" or type(stringOrNumber) == "number", "The variable must either be a string or a number")

-- If stringOrNumber were to be set to a boolean value (true / false) it would error.

if type(stringOrNumber) == "string" then
    local string = stringOrNumber -- ok
    local number = stringOrNumber -- ok
end

if type(stringOrNumber) ~= "string" then
    local string = stringOrNumber -- ok
    local number = stringOrNumber -- ok
end
```

I also somewhat do this for some of my programs but I have my own way of doing it, I use `assert` instead of this new type checking syntax (that is for Luau only), which I just showed you an example of in the code block above. For [reference](https://github.com/Exunys/Config-Library/blob/main/Main.lua#L124):

![image](https://github.com/user-attachments/assets/9b926f01-6bfb-4367-89c7-cab6afccf431)

This is actually an interesting discussion and I am somewhat surprised someone would ask me this. Also thank you for staying loyal to my work and that you could actually learn something!

**Comment by Exunys** [comment]
Inactive ticket + this is not an issue, feel free to comment though.
